language: node_js
node_js:
  - "5"
  - "4"
before_script:
  - psql -U postgres -c 'DROP DATABASE IF EXISTS collectiva_test;'
  - psql -U postgres -c 'CREATE DATABASE collectiva_test;'
  - psql -U postgres -c "CREATE USER collectiva WITH PASSWORD 'collectiva';"
  - psql -U postgres -c 'GRANT ALL PRIVILEGES ON DATABASE collectiva_test to collectiva;'
env:
  - CXX=g++-4.8
addons:
  postgresql: "9.4"
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
services:
  - postgresql
