- hosts: all
  sudo: yes
  roles:
    - { role: common }
    - { role: nodesource.node }
    - { role: sendmail}
    - { role: postgres, db_names: ["collectiva", "collectiva_test"] }
    - { role: vagrant }